version: 2
jobs:
  build:
    working_directory: ~/terminal
    docker:
      - image: xploitednoob/build-apk:latest
    environment:
          JVM_OPTS: -Xmx3200m
          TERM: dumb
          ANDROID_HOME: /home/builder/lib/android-sdk
          ANDROID_SDK_ROOT: /home/builder/lib/android-sdk
    steps:
      - checkout
      - run:
          name: Install SDK Packages
          command: |
            echo 'sdk.dir=/home/builder/lib/android-sdk' >> local.properties
            echo 'ndk.dir=/home/builder/lib/android-ndk' >> local.properties
            ./tools/install-sdk-packages
      - run:
          name: Build Debug APK
          command: ./gradlew assembleDebug
      - run:
          name: Build Release APK
          command: ./gradlew assembleRelease
      - run:
          name: Sign Generated APKs
          command: |
            git clone http://github.com/xploitednoob/signapk.git
            cd term/build/outputs/apk
            java -jar /home/builder/terminal/signapk/signapk.jar /home/builder/terminal/signapk/publickey.x509.pem /home/builder/terminal/signapk/publickey.pk8 term-release-unsigned.apk terminal-release.apk
            java -jar /home/builder/terminal/signapk/signapk.jar /home/builder/terminal/signapk/publickey.x509.pem /home/builder/terminal/signapk/publickey.pk8 term-debug.apk terminal-debug.apk
      - store_artifacts:
          name: Store Release APK
          path: ./term/build/outputs/apk/terminal-release.apk
          destination: terminal-release.apk
      - store_artifacts:
          name: Store Debug APK
          path: ./term/build/outputs/apk/terminal-debug.apk
          destination: terminal-debug.apk
